# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67bac639b37b34994e8fa3af28d6b77bd31263c3f53d5cb599aeb13f41c496381971979efd317a24cbca5235cbbbafaf0b7f18734856fb12330ac64f2bfb1143

test:
  secret_key_base: 5d83213782659dfd72175dfbe3def461d3cbd6de1a97d6fbbdbbc441460cb996452bedddbb072fc8bd5c29f6bd52406dc6646b368e9c3d68f15749f5b58f5bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
