# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 781c484b3bec4473ca519cde18cd77d55e38bae238bd634e163b67ed744cad9544b1df42ed4fc4f9a55e0ac78b320adb2df65554dcf3876a576533a50cf2c368

test:
  secret_key_base: adae9bd22c7ea6d5b2d4edbd069008dff8a96ec1eeb28add963e07e6a99a743bb43fe5e9064f08fde8ffcb2f1b1d48742c23cdbab09bb06d8b2821594c991b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
